"""remove settigns

Revision ID: 2e9def2eacde
Revises: fdde38cac3f8
Create Date: 2026-09-30 12:51:06.175908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2e9def2eacde'
down_revision: Union[str, Sequence[str], None] = 'fdde38cac3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_settings_group_id'))

    op.drop_table('group_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.VARCHAR(), nullable=True),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_settings_group_id'), ['group_id'], unique=1)

    # ### end Alembic commands ###
