"""add invite code to groups

Revision ID: cfa4839a85ef
Revises: edd974f16b2f
Create Date: 2026-09-28 22:34:48.168305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa4839a85ef'
down_revision: Union[str, Sequence[str], None] = 'edd974f16b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('invite_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_groups_invite_code'), 'groups', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_invite_code'), table_name='groups')
    op.drop_column('groups', 'invite_code')
    # ### end Alembic commands ###
