"""initial

Revision ID: d9634a8a45a7
Revises: 
Create Date: 2026-09-28 17:13:43.121936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9634a8a45a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('teacher', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_group_id'), 'exams', ['group_id'], unique=False)
    op.create_table('group_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_settings_group_id'), 'group_settings', ['group_id'], unique=True)
    op.create_table('mail_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('preview', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('auto_forward', sa.Boolean(), nullable=True),
    sa.Column('forwarded_at', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_items_group_id'), 'mail_items', ['group_id'], unique=False)
    op.create_table('mailboxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('auto_forward', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailboxes_group_id'), 'mailboxes', ['group_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('max_user_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_group_id'), 'users', ['group_id'], unique=False)
    op.create_index(op.f('ix_users_max_user_id'), 'users', ['max_user_id'], unique=True)
    op.create_table('debts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_group_id'), 'debts', ['group_id'], unique=False)
    op.create_index(op.f('ix_debts_student_id'), 'debts', ['student_id'], unique=False)
    op.create_table('exam_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_materials_exam_id'), 'exam_materials', ['exam_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('max_file_id', sa.String(), nullable=True),
    sa.Column('max_message_id', sa.String(), nullable=True),
    sa.Column('max_chat_id', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_author_id'), 'materials', ['author_id'], unique=False)
    op.create_index(op.f('ix_materials_group_id'), 'materials', ['group_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_author_id'), 'reminders', ['author_id'], unique=False)
    op.create_index(op.f('ix_reminders_group_id'), 'reminders', ['group_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_author_id'), 'tasks', ['author_id'], unique=False)
    op.create_index(op.f('ix_tasks_group_id'), 'tasks', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_group_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_author_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_reminders_group_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_author_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_materials_group_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_author_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_exam_materials_exam_id'), table_name='exam_materials')
    op.drop_table('exam_materials')
    op.drop_index(op.f('ix_debts_student_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_group_id'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_users_max_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_group_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mailboxes_group_id'), table_name='mailboxes')
    op.drop_table('mailboxes')
    op.drop_index(op.f('ix_mail_items_group_id'), table_name='mail_items')
    op.drop_table('mail_items')
    op.drop_index(op.f('ix_group_settings_group_id'), table_name='group_settings')
    op.drop_table('group_settings')
    op.drop_index(op.f('ix_exams_group_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_table('groups')
    # ### end Alembic commands ###
