"""add notifications_log

Revision ID: edd974f16b2f
Revises: d9634a8a45a7
Create Date: 2026-09-28 21:17:27.763674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd974f16b2f'
down_revision: Union[str, Sequence[str], None] = 'd9634a8a45a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_log_entity_id'), 'notifications_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_log_entity_type'), 'notifications_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_notifications_log_kind'), 'notifications_log', ['kind'], unique=False)
    op.create_index(op.f('ix_notifications_log_user_id'), 'notifications_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_log_user_id'), table_name='notifications_log')
    op.drop_index(op.f('ix_notifications_log_kind'), table_name='notifications_log')
    op.drop_index(op.f('ix_notifications_log_entity_type'), table_name='notifications_log')
    op.drop_index(op.f('ix_notifications_log_entity_id'), table_name='notifications_log')
    op.drop_table('notifications_log')
    # ### end Alembic commands ###
