"""add targe_students_ids and completed_by columns to reminders

Revision ID: fdde38cac3f8
Revises: cfa4839a85ef
Create Date: 2026-09-29 14:22:01.396551

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdde38cac3f8"
down_revision: Union[str, Sequence[str], None] = "cfa4839a85ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reminders", sa.Column("target_student_ids", sa.JSON(), nullable=True))
    op.add_column("reminders", sa.Column("completed_by", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reminders", "completed_by")
    op.drop_column("reminders", "target_student_ids")
    # ### end Alembic commands ###
